<?php

global $c2pOptions;

// do not edit this file
// all values are set via config settings or upon use

$c2pOptions['SSLcert'] = '';

$c2pOptions['SSLkey'] = '';

$c2pOptions['secret'] = '';

$c2pOptions['notificationEmail'] = '';

$c2pOptions['notificationURL'] = '';

$c2pOptions['redirectURL'] = '';

$c2pOptions['currency'] = '';

$c2pOptions['physical'] = 'true';

$c2pOptions['fullNotifications'] = 'true';

$c2pOptions['defaultCoin'] = '1'; 

$c2pOptions['verifyPos'] = true; 

?>